crude/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('reports.urls')),
]

urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports/urls.py
from django.urls import path
from . views import report_view,delete_view,ReportUpdateView,HomeView,SelectView

app_name='reports'

urlpatterns = [
    path('',HomeView.as_view(),name="home"),
    path('reports/',SelectView.as_view(),name='select_view'),
    path('reports/<str:productionline>/',report_view,name='report_view'),
    path('reports/delete/<pk>',delete_view,name='delete_view'),
    path('reports/<str:productionline>/<pk>/update/',ReportUpdateView.as_view(),name='update-view')
]

reports/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from products.models import Product
from areas.models import ProductionLine
from categories.models import Category
import random
from django.shortcuts import reverse
#hours =[('1', '1'), ('2', '2'), ('3', '3')]
hours = ([(str(x),str(x)) for x in range(1,25)])

el = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z',1,2,3,4,5,6,7,8,9]

class Report(models.Model):
    day =models.DateTimeField(default=timezone.now)
    start_hour =models.CharField(max_length=2,choices=hours)
    end_hour = models.CharField(max_length=2,choices=hours)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    #product
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    plan = models.PositiveIntegerField()
    execution = models.PositiveIntegerField()
    #productionline
    productionline = models.ForeignKey(ProductionLine,on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}-{}-{}".format(self.start_hour,self.end_hour,self.product)

    def get_day(self):
        return self.day.strftime('%Y/%m/%d')

    def get_absolute_url(self):
        return reverse("reports:update-view", kwargs={"productionline": self.productionline,"pk":self.pk,})
    

    class Meta:
        ordering = ('-created',)

def random_code():
    random.shuffle(el)
    code = [str(x) for x in el[:12]]
    str_code = ''.join(code)
    return str_code

class ProblemReporting(models.Model):
    category = models.ForeignKey(Category,on_delete=True)
    description = models.TextField()
    problem_id = models.CharField(max_length=12,unique=True,default=random_code)
    breakdown = models.PositiveIntegerField()
    public = models.BooleanField(default=False)
    report = models.ForeignKey(Report,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}-{}".format(self.category.name,self.description[:20])
    

reports/forms.py
from django import forms
from .models import Report,ProblemReporting
from areas.models import ProductionLine
from django.shortcuts import get_object_or_404


class ReportResultForm(forms.Form):
    production_line = forms.ModelChoiceField(queryset=ProductionLine.objects.all())
    day = forms.CharField(widget=forms.DateTimeInput(attrs={'class':'datepicker'}))


class ReportSelectLineForm(forms.Form):
    production_line = forms.ModelChoiceField(
        queryset=ProductionLine.objects.none(), label='')

    def __init__(self, user, *args, **kwargs):
        self.user = user
        print(user)
        super(ReportSelectLineForm, self).__init__(*args, **kwargs)
        self.fields['production_line'].queryset = ProductionLine.objects.filter(team_leader__user__username=user)
       

class ReportForm(forms.ModelForm):

    class Meta:
        model = Report
        # fields = '__all__'
        exclude = ('user','productionline',)

    def __init__(self, *args, **kwargs):
        productionline =kwargs.pop('productionline',None)
        super().__init__(*args, **kwargs)
        if productionline is not None:
            line = get_object_or_404(ProductionLine,name=productionline)
            self.fields['product'].queryset = line.products.all()


    
class ProblemReportingForm(forms.ModelForm):

    class Meta:
        model = ProblemReporting
       # fields = '__all__'
        exclude = ('user','report','problem_id',)

reports/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .forms import ProblemReportingForm,ReportForm,ReportSelectLineForm,ReportResultForm
from .models import Report
from areas.models import ProductionLine
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView,FormView
from django.urls import reverse_lazy

class SelectView(FormView):
    template_name = 'reports/select.html'
    form_class = ReportResultForm
    success_url = reverse_lazy('reports:home')

    def form_valid(self, form):
        self.request.session['day'] = self.request.POST.get('day',None)
        print(self.request.session['day'])
        return super(SelectView,self).form_valid(form)


    
class HomeView(FormView):
    template_name = 'reports/home.html'
    form_class = ReportSelectLineForm

    def get_form_kwargs(self):
        kwargs = super(HomeView,self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def post(self,*args, **kwargs):
        prod_line = self.request.POST.get("prod_line")
        return redirect('reports:report_view',productionline=prod_line)


class ReportUpdateView(UpdateView):
    model = Report
    form_class = ReportForm
    template_name = 'reports/update.html'

    def get_success_url(self):
        return self.request.path


@login_required
def delete_view(request,*args,**kwargs):
    r_id =kwargs.get('pk')
    obj =Report.objects.get(id=r_id)
    obj.delete()
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
def report_view(request,productionline):
    templates = 'reports/index.html'
    rform = ReportForm(request.POST or None,productionline=productionline)
    pform = ProblemReportingForm(request.POST or None)
   
    queryset = Report.objects.filter(productionline__name =productionline)
    r_id = request.POST.get('report_id')
    line = get_object_or_404(ProductionLine,name=productionline)
    # print(line)

    if 'btn_sub_report_form' in request.POST:
        print(request.user)
        if rform.is_valid():
            obj =rform.save(commit=False)
            obj.user = request.user
            obj.productionline = line
            obj.save()
            return redirect(request.META.get('HTTP_REFERER'))

    elif 'btn_sub_problem_report' in request.POST:
        if pform.is_valid():
            report = Report.objects.get(id=r_id)
            obj = pform.save(commit=False)
            obj.user = request.user
            obj.report = report
            obj.save()
            return redirect(request.META.get('HTTP_REFERER'))

       
   
    context ={
        'rform':rform,
        'pform':pform,
        'object_list':queryset
    }
    return render(request,templates,context)

reports/templates/reports/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}home view{% endblock title %}
{% block content %}
  <div class="col-md-12 p-1 mt-5">
    <div class="col-6 mx-auto m-5 text-primary  " >
        <div class="text-center h1 M-5">
            Welcome to Report
        </div>
        
        {% if request.user.is_authenticated %}
             <div class="text-center h4 mb-4">Select a production line to begin</div>
             <form action="" class="text-center" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <input type="hidden" name="prod_line" id="prod_line">
                <button type="submit" name="submit" class="btn btn-primary btn-block">Submit</button>
            </form>
        {% else %}
            <div class="text-center  h3">Login To Begin</div>
        {% endif %}
            
        
        
    </div>
  </div>

{% endblock content %}

{% block script %}
    <script>
        $('#id_production_line').on('change',function(){
            const production_line = $('#id_production_line option:selected').text();
            console.log(production_line);
            $('#prod_line').val(production_line);
        });
    </script> 
{% endblock script %}
    

reports/templates/reports/index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
   report page
{% endblock title %}

{% block content %}

 <div class="row mt-5">
   <div class="col-md-2 box-shadow">
    <h4>Report</h4>
    <form action="" method="POST">
        {% csrf_token %}
        {{rform|crispy}}
        <button type="submit" name="btn_sub_report_form" class="btn btn-primary  w-100 "><i class="fa fa-paper-plane"></i> Send</button>
    </form>
    
   </div>
   <div class="col-md-10">
      <div style="overflow-y:scroll; height:80vh" class="w-100 bg-ligtht">
        <table class="table table-bordered">
            <thead class="thead-light ">
              <tr class="text-center">
                <th scope="col">Day</th>
                <th scope="col">Start</th>
                <th scope="col">End</th>
                <th scope="col">Product</th>
                <th scope="col">Plan</th>
                <th scope="col">Execution</th>
                <th scope="col">Line</th>
                <th scope="col">Problem</th>
                <th scope="col">edit</th>
                <th scope="col">delete</th>
              </tr>

            </thead>
            <tbody>
              {% for obj in object_list %}
              <tr class="text-center">
                <td> {{obj.get_day}}</td>
                <td> {{obj.start_hour}}</td>
                <td> {{obj.end_hour}}</td>
                <td> {{obj.product}}</td>
                <td> {{obj.plan}}</td>
                <td> {{obj.execution}}</td>
                <td> {{obj.productionline}}</td>
                <td class="fit">
                  <button class="btn btn-warning open-modal" data-toggle="modal" data-target="#problem-reporting" data-url="{{obj.id}}"><i class="fas fa-exclamation-triangle"></i></button>
                </td>
                <td class="fit">
                  <a href="{{obj.get_absolute_url}}"><button class="btn btn-info"><i class="fas fa-edit"></i></button></a>
                </td>
                <td class="fit">
                  <a href="{% url 'reports:delete_view' pk=obj.id %}"><button class="btn btn-danger"><i class="fas fa-trash"></i></button></a>
                </td>
               
               


              </tr>
               
              {% endfor %}

            </tbody>
        </table>

      </div>
   </div>
 </div>

   <!-- The problem reporting Modal -->
   <div class="modal fade" id="problem-reporting">
    <div class="modal-dialog">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Problem Reporting Form</h4>
          <button type="button" class="close" data-dismiss="modal">×</button>
        </div>
        <form action="" method="POST">
        <!-- Modal body -->
        <div class="modal-body">
            {% csrf_token %}
            {{pform|crispy}}
            <input type="hidden" id="report_id" name="report_id">
         
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          <button class="btn btn-primary" name="btn_sub_problem_report" type="submit">Save</button>
        </div>

      </form>
        
      </div>
    </div>
  </div>
 
  <!-- script for modal -->

{% endblock content %}

{% block script %}
<script>
  $('.open-modal').on('click',function(){
    const report_id = $(this).attr('data-url');
    $('#report_id').val(report_id);
    console.log(report_id);
  });
</script>
{% endblock script %}

reports/templates/reports/select.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
   Report Select View
{% endblock title %}
{% block content %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

   <div class="col-md-12 m-5 p-2">
       <div class="col-md-6 mx-auto">
           <div class="text-center h4 m-2">
                Select to View Report Summery 
           </div>
            <form action="" method="post">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" class="btn btn-primary text-center" name="submit" value="Submit">
            </form>
       </div>
   </div>

{% endblock content %}
{% block script %}
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $(function(){
        $('.datepicker').datepicker({'dateFormat':'yy-mm-dd'}).val();
    });
</script>
{% endblock script %}

reports/templates/reports/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Update view{% endblock title %}
{% block content %}
 
<div class="col-9 mx-auto">
    <div class="card p-4">
        <div class="text-mute mb-4 h4">
            production line {{object.productionline}}
        </div>
        <form action="" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-primary" type="submit">Update</button>
        </form>

    </div>
</div>





{% endblock content %}